name: Solución-2023-2-DevOps-AUT-Grupo-1

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 12

      - name: Install Node.js dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
    
  run-tests:
      name: Run Tests
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
    
        - name: Use Node.js v18
          uses: actions/setup-node@v4
          with:
            node-version: '18'
    
        - name: Install Angular CLI
          run: npm install -g @angular/cli
    
        - name: Install dependencies
          run: npm install
    
        - name: Run tests
          run: ng test --watch=false --browsers=ChromeHeadless
    
        - name: Print Test Results
          run: |
            echo "Tests ejecutados correctamente"

  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js v18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Angular CLI
        run: npm install -g @angular/cli
          
      - name: Install dependencies
        run: npm install

      - name: Lint Action   
        uses: wearerequired/lint-action@v2.3.0

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true

      - name: Run tests
        run: ng test --watch=false --browsers=ChromeHeadless

      - name: Build
        run: npm run build

      - name: List Modified Files
        run: |
          echo "Archivos modificados:"
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}

      - name: Print Pipeline Finished
        run: echo "La pipeline ha finalizado exitosamente."
